---
title: "R Code"
author: "Oladayo"
date: "2024-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Read in the dataset ‘em_house_prices.csv’
em_house_prices <- read.csv('./dataset/em_house_prices.csv', header = TRUE)
```

```{r}
#Set the dataset to be time series data
em_house_prices_ts <- ts(em_house_prices$average_price_gbp, start = 2010, frequency = 12)
```

```{r}
#Produce a time plot of the time series data ‘em_house_prices_ts’
ts.plot(em_house_prices_ts , ylab = 'Mean House Prices (GBP)', xlab = 'Year', main = 'Monthly Average House Prices')
```

```{r}
#Set the R graphics device to contain two plots (1 row, 2 columns)
par(mfrow = c(1,2))
#Plot the sample ACF of the time series data
acf(em_house_prices_ts, ylab = 'Sample ACF', main = 'Sample ACF')
#Plot the sample PACF of the time series data
pacf(em_house_prices_ts, ylab = 'Sample PACF', main = 'Sample PACF')
```

```{r}
#Take the first difference (lag 12) of the time series data to remove seasonality
em_house_prices_ts_diff <- diff(em_house_prices_ts, lag = 12)
#Set the R graphics device to contain two plots (1 row, 1 column)
par(mfrow = c(1,1))
#Produce a time plot of the first difference (lag 12) time series data ‘em_house_prices_ts_diff’
ts.plot(em_house_prices_ts_diff, ylab = 'House Price Difference (GBP)', xlab = 'Year', main = 'First Differenced House Prices (Lag 12)')
```

```{r}
#Set the R graphics device to contain 1 plot (1 row, 2 columns)
par(mfrow = c(1,2))
#Plot the sample ACF of the first difference time series data
acf(em_house_prices_ts_diff, ylab = 'Sample ACF', main = 'Sample ACF of First Differenced House Prices (Lag 12)')
#Plot the sample PACF of the first difference time series data
pacf(em_house_prices_ts_diff, ylab = 'Sample PACF', main = 'Sample PACF of First Differenced House Prices (Lag 12)')
```

```{r}
#Take the second difference of the time series data
em_house_prices_ts_diff2 <- diff(em_house_prices_ts_diff)
#Set the R graphics device to contain two plots (1 row, 1 column)
par(mfrow = c(1,1))
#Produce a time plot of the second difference time series data ‘em_house_prices_ts_diff2’
ts.plot(em_house_prices_ts_diff2, ylab = 'House Price Difference (GBP)', xlab = 'Year', main = 'Second Differenced House Prices')
```

```{r}
#Set the R graphics device to contain 1 plot (1 row, 2 columns)
par(mfrow = c(1,2))
#Plot the sample ACF of the second difference time series data
acf(em_house_prices_ts_diff2, ylab = 'Sample ACF', main = 'Sample ACF of Second Differenced House Prices')
#Plot the sample PACF of the second difference time series data
pacf(em_house_prices_ts_diff2, ylab = 'Sample PACF', main = 'Sample PACF of Second Differenced House Prices')
```

```{r}
#Fit an ARIMA(0,1,1) x (0,1,1)12 model to the time series data ‘em_house_prices_ts’
arima011011_model <- arima(em_house_prices_ts, order = c(0,1,1), seasonal = list(order = c(0,1,1), period = 12), method = 'ML')
#Call the arima011011_model ARIMA(0,1,1) x (0,1,1)12 to get it estimated parameters
arima011011_model
```

```{r}
#Extract the residuals of the arima011011_model
arima011011_residuals <- residuals(arima011011_model)
#Set the R graphics device to contain 1 plot (1 row, 2 columns)
par(mfrow = c(1,2))
#Produce a time plot of the arima011011_model residuals
ts.plot(arima011011_residuals, ylab = 'Residuals', xlab = 'Year', main = 'Residuals: ARIMA(0,1,1) x (0,1,1)12')
#Plot the sample ACF of the arima011011_model residuals
acf(arima011011_residuals, ylab = 'Sample ACF', main = 'Sample ACF: ARIMA(0,1,1) x (0,1,1)12 Residuals')
```

```{r}
#Declare the Ljung-Box test variable term
LB_test<-function(resid,max.k,p,q){
lb_result<-list()
df<-list()
p_value<-list()
for(i in (p+q+1):max.k){
lb_result[[i]]<-Box.test(resid,lag=i,type=c("Ljung-Box"),fitdf=(p+q))
df[[i]]<-lb_result[[i]]$parameter
p_value[[i]]<-lb_result[[i]]$p.value
}
df<-as.vector(unlist(df))
p_value<-as.vector(unlist(p_value))
test_output<-data.frame(df,p_value)
names(test_output)<-c("deg_freedom","LB_p_value")
return(test_output)
}
```

```{r}
#Perform Ljung-Box tests for the arima011011 (ARIMA(0,1,1) x (0,1,1)12) model residuals
ARIMA011011.LB <- LB_test(arima011011_residuals, max.k = 11, p = 0, q = 1)
#Set the R graphics device to contain 1 plot (1 row, 1 column)
par(mfrow = c(1,1))
#Produce a plot of P-values against the degrees of freedom and add a blue dashed line at 0.05
plot(ARIMA011011.LB$deg_freedom, ARIMA011011.LB$LB_p_value, xlab = 'Degrees of freedom', ylab = 'P-value', main = 'Ljung-Box test P-values: ARIMA(0,1,1) x (0,1,1)12 Residuals', ylim = c(0,1))
abline(h = 0.05, col = 'blue', lty = 2)
```

```{r}
#Fit an ARIMA(1,1,0) x (1,1,0)12 model to the time series data ‘em_house_prices_ts’
arima110110_model <- arima(em_house_prices_ts, order = c(1,1,0), seasonal = list(order = c(1,1,0), period = 12), method = 'ML')
#Call the arima110110_model (ARIMA(0,1,1) x (0,1,1)12) to get it estimated parameters
arima110110_model
```

```{r}
#Extract the residuals of the arima110110_model
arima110110_residuals <- residuals(arima110110_model)
#Set the R graphics device to contain 1 plot (1 row, 2 columns)
par(mfrow = c(1,2))
#Produce a time plot of the arima110110_model residuals
ts.plot(arima110110_residuals, ylab = 'Residuals', xlab = 'Year', main = 'Residuals: ARIMA(1,1,0) x (1,1,0)12')
#Plot the sample ACF of the arima110110_model residuals
acf(arima110110_residuals, ylab = 'Sample ACF', main = 'Sample ACF: ARIMA(1,1,0) x (1,1,0)12 Residuals')
```

```{r}
#Perform Ljung-Box tests for the arima110110 (ARIMA(1,1,0) x (1,1,0)12) model residuals
ARIMA110110.LB <- LB_test(arima110110_residuals, max.k = 11, p = 1, q = 0)
#Set the R graphics device to contain 1 plot (1 row, 1 column)
par(mfrow = c(1,1))
#Produce a plot of P-values against the degrees of freedom and add a blue dashed line at 0.05
plot(ARIMA110110.LB$deg_freedom, ARIMA110110.LB$LB_p_value, xlab = 'Degrees of freedom', ylab = 'P-value', main = 'Ljung-Box test P-values: ARIMA(1,1,0) x (1,1,0)12 Residuals', ylim = c(0,1))
abline(h = 0.05, col = 'blue', lty = 2)
```

```{r}
#Fit an ARIMA(1,1,1) x (1,1,1)12 model to the time series data ‘em_house_prices_ts’
arima111111_model <- arima(em_house_prices_ts, order = c(1,1,1), seasonal = list(order = c(1,1,1), period = 12), method = 'ML')
#Call the arima111111_model (ARIMA(1,1,1) x (1,1,1)12) to get it estimated parameters
arima111111_model
```

```{r}
#Extract the residuals of the arima111111_model
arima111111_residuals <- residuals(arima111111_model)
#Set the R graphics device to contain 1 plot (1 row, 2 columns)
par(mfrow = c(1,2))
#Produce a time plot of the arima111111_model residuals
ts.plot(arima111111_residuals, ylab = 'Residuals', xlab = 'Year', main = 'Residuals: ARIMA(1,1,1) x (1,1,1)12')
#Plot the sample ACF of the arima111111_model residuals
acf(arima111111_residuals, ylab = 'Sample ACF', main = 'Sample ACF: ARIMA(1,1,1) x (1,1,1)12 Residuals')
```

```{r}
#Perform Ljung-Box tests for the arima111111 (ARIMA(1,1,1) x (1,1,1)12) model residuals
ARIMA111111.LB <- LB_test(arima111111_residuals, max.k = 11, p = 1, q = 1)
#Set the R graphics device to contain 1 plot (1 row, 1 column)
par(mfrow = c(1,1))
#Produce a plot of P-values against the degrees of freedom and add a blue dashed line at 0.05
plot(ARIMA111111.LB$deg_freedom, ARIMA111111.LB$LB_p_value, xlab = 'Degrees of freedom', ylab = 'P-value', main = 'Ljung-Box test P-values: ARIMA(1,1,1) x (1,1,1)12 Residuals', ylim = c(0,1))
abline(h = 0.05, col = 'blue', lty = 2)
```

```{r}
#Fit an ARIMA(1,1,2) x (1,1,2)12 model to the time series data ‘em_house_prices_ts’
arima112112_model <- arima(em_house_prices_ts, order = c(1,1,2), seasonal = list(order = c(1,1,2), period = 12), method = 'ML')
#Call the arima112112_model (ARIMA(1,1,2) x (1,1,2)12) to get it estimated parameters
arima112112_model
```

```{r}
#Extract the residuals of the arima112112_model
arima112112_residuals <- residuals(arima112112_model)
#Set the R graphics device to contain 1 plot (1 row, 2 columns)
par(mfrow = c(1,2))
#Produce a time plot of the arima112112_model residuals
ts.plot(arima112112_residuals, ylab = 'Residuals', xlab = 'Year', main = 'Residuals: ARIMA(1,1,2) x (1,1,2)12')
```

```{r}
#Perform Ljung-Box tests for the arima112112 (ARIMA(1,1,2) x (1,1,2)12) model residuals
ARIMA112112.LB <- LB_test(arima112112_residuals, max.k = 11, p = 1, q = 2)
#Set the R graphics device to contain 1 plot (1 row, 1 column)
par(mfrow = c(1,1))
#Produce a plot of P-values against the degrees of freedom and add a blue dashed line at 0.05
plot(ARIMA112112.LB$deg_freedom, ARIMA112112.LB$LB_p_value, xlab = 'Degrees of freedom', ylab = 'P-value', main = 'Ljung-Box test P-values: ARIMA(1,1,2) x (1,1,2)12 Residuals', ylim = c(0,1))
abline(h = 0.05, col = 'blue', lty = 2)
```

```{r}
#Fit an ARIMA(1,1,2) x (0,1,1)12 model to the time series data ‘em_house_prices_ts’
arima112011_model <- arima(em_house_prices_ts, order = c(1,1,2), seasonal = list(order = c(0,1,1), period = 12), method = 'ML')
#Call the arima112011_model (ARIMA(1,1,2) x (0,1,1)12) to get it estimated parameters
arima112011_model
```

```{r}
#Extract the residuals of the arima112011_model
arima112011_residuals <- residuals(arima112011_model)
#Set the R graphics device to contain 1 plot (1 row, 2 columns)
par(mfrow = c(1,2))
#Produce a time plot of the arima112011_model residuals
ts.plot(arima112011_residuals, ylab = 'Residuals', xlab = 'Year', main = 'Residuals: ARIMA(1,1,2) x (0,1,1)12')
#Plot the sample ACF of the arima112011_model residuals
acf(arima112011_residuals, ylab = 'Sample ACF', main = 'Sample ACF: ARIMA(1,1,2) x (0,1,1)12 Residuals')
```

```{r}
#Perform Ljung-Box tests for the arima112011 (ARIMA(1,1,2) x (0,1,1)12) model residuals
ARIMA112011.LB <- LB_test(arima112011_residuals, max.k = 11, p = 1, q = 2)
#Set the R graphics device to contain 1 plot (1 row, 1 column)
par(mfrow = c(1,1))
#Produce a plot of P-values against the degrees of freedom and add a blue dashed line at 0.05
plot(ARIMA112011.LB$deg_freedom, ARIMA112011.LB$LB_p_value, xlab = 'Degrees of freedom', ylab = 'P-value', main = 'Ljung-Box test P-values: ARIMA(1,1,2) x (0,1,1)12 Residuals', ylim = c(0,1))
abline(h = 0.05, col = 'blue', lty = 2)
```

```{r}
#Produce a Forecast for the next 6 months (h = 6)
library(forecast)
forecast_6m <-forecast(em_house_prices_ts, h = 6, model = arima112011_model, level = 95)
#Plot the Forecast
autoplot(forecast_6m, ylab = 'Average House Prices (GBP) ', xlab = 'Year', main = 'January-June 2020 Forecasts from ARIMA(1,1,2)(0,1,1)[12] ')
```

```{r}
#Produce average(mean) forecast values
forecast_6m$mean
#Produce upper limit of forecast values
forecast_6m$upper
#Produce lower limit of forecast values
forecast_6m$lower
```

